[[headers]]
  for = "/azkar"
  [headers.values]
	cache-control = "max-age=1, public"
[[headers]]
  for = "/*"
  [headers.values]
	cache-control = "max-age=1, public"
[[redirects]]
  from = "/*"
  to = "/"
  status = 200